spring:
  application:
    name: config-client
  cloud:
    config:
      label: master #远程仓库的分支
      profile: dev #环境
      uri: http://localhost:8888/ #配置服务中心的网址
      discovery:
        enabled: true
        service-id: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8770

