eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes: 
    service-ribbon: /api-ribbon/**
    service-feign: /api-feign/**

    #api-a:
      #path: /api-a/**
      #serviceId: service-ribbon
    #api-b:
      #path: /api-b/**
      #serviceId: service-feign
